### ISSUE TITLE
GraphsplainingService: Recommend Indexes based out of EXPLAIN patterns

### ISSUE THREAD

**Issue by mdfrenchman** [jsmccrumb/Graphsplaining#8]
Service should be able to:

- [x] recommend indexes based on explain
- [x] doesn't recommend index that already exists

**Comment by jsmccrumb** [comment]
Could have a (explain:Explain)-[:COULD_INDEX]->(:Plan)
(maybe a COULD_INDEX_PROPERTY and COULD_INDEX_LABEL) pointing to the node label scan (to grab label) and the following filter or value hash join (there was a case on neo4j slack where someone had a slow query that was 2 node label scans followed by a value hash join and they needed to add an index on it) -- Frontend report would only pull the most recent explain for a query (so after index added it could be re-explained and no longer show up)... and optionally have stats from query log if available (ave run time, times run, fastest time, slowest time?)
